### ISSUE TITLE
Course has all shifts incorrectly shown as being lectured all in the same campus

### ISSUE THREAD

**Issue by sfondev** [Criador-Horarios/Criador-Horarios#93]
## Description of the issue:
Picked course shows all lectures and labs as being lectured on one of the campus, despite some of them being lectured on the other campus.

## Additional details:
- Initially I found only one course,ADSI/AOBD,exhibiting this specific behavior so I didn't know for sure if the problem extended to others, but there is at least another one where the same behavior is shown,SEC/HDS/SDTF.
-  All the testing was done on Firefox (version 122.0.1) on private and normal tabs with both showing the same behavior 

## Reproduction steps:
1.  Pick a degree that has one of the affected courses, for ADSI/AOBD lets pick MEIC-T as an example
2.  Pick the course ADSI/AOBD
3.  All possible lectures and labs are displayed and we can see that every shift shown is supposedly being lectured at campus Alameda which is incorrect as some of them are lectured on the campus Tagus Park

**Comment by powy-e** [comment]
## Problem:
Fenix's v2 api does not return the `TopLevelSpace` (campus) as opposed to v1. As such, the campus is assumed to be the one from the first degree associated with the class. This assumption is incorrect.

## Possible Solution:
To keep using v2, another api query must be made, in order to retrieve the campus where the lecture is held.

I'm working on a fix using this approach

**Comment by masterzeus05** [comment]
Looking into this!
